name: Linux Container Node Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: reestr1.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t reestr1.azurecr.io/lab4-api:${{ github.sha }}
        docker push reestr1.azurecr.io/lab4-api:${{ github.sha }}     

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'lab4-api'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'reestr1.azurecr.io/lab4-api:${{ github.sha }}'
